name: flutter_research
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.2
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  otp_text_field: ^1.1.3
  otpview: ^0.0.2
  date_picker_timeline: ^1.2.3
  weekly_date_picker: ^1.3.0
  onetrust_publishers_native_cmp: ^6.38.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
